# Generated by Django 2.1.7 on 2019-04-01 09:33

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190401_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_profile_image, verbose_name='Аватарка'),
        ),
    ]
