# Generated by Django 2.1.7 on 2019-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vision',
            field=models.BooleanField(default=True, null=True, verbose_name='Отображение для всех'),
        ),
    ]
