# Generated by Django 2.1.7 on 2019-03-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190311_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='template_name',
            field=models.CharField(default='news/post-detail.html', max_length=200, verbose_name='Шаблон статьи'),
        ),
    ]
