# Generated by Django 2.1.7 on 2019-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190311_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template_name',
            field=models.CharField(default='news/post-list.html', max_length=100, verbose_name='Название шаблона'),
        ),
    ]
