# Generated by Django 2.1.7 on 2019-04-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190401_1344'),
        ('news', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery', verbose_name='Галерея'),
        ),
    ]
