# Generated by Django 2.1.7 on 2019-03-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_template_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vision',
            new_name='is_private',
        ),
    ]
