# Generated by Django 2.1.7 on 2019-04-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190402_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата написания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderation',
            field=models.BooleanField(default=False, null=True, verbose_name='Разрешено к публикации'),
        ),
    ]
