# Generated by Django 2.1.7 on 2019-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190311_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pagination',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Количество статей на страницу'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post/', verbose_name='Картинка статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
    ]
