# Generated by Django 2.1.7 on 2019-03-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('subject', models.CharField(max_length=30, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'Контакная форма',
                'verbose_name_plural': 'Контакные формы',
                'ordering': ['name'],
            },
        ),
    ]
